version: '1'
services:
  bot:
    build: ./bot
    depends_on:
      - postgres
      - lavalink
      - redis
    env_file: .env
    restart: always
  web:
    build: ./web
    env_file: .env
    restart: always
    depends_on:
      - postgres
      - redis
  lavalink:
    build: ./lavalink
  redis:
    image: redis:alpine
  postgres:
    image: postgres:9-alpine
    environment:
      - POSTGRES_USER=dash
      - POSTGRES_PASSWORD=ankh
      - POSTGRES_DB=ankh